// This file is auto-generated by massdriver from your massdriver.yaml file.
// Any changes made directly to this file will be overwritten on the next build.
// To opt a variable out of regeneration, move it to another file (e.g. variables.tf).
variable "aws_authentication" {
  type = object({
    arn         = string
    external_id = optional(string)
  })
}
variable "fargate" {
  type = object({
    enabled    = optional(bool)
    namespaces = optional(list(string))
  })
  default = null
}
variable "k8s_version" {
  type = string
}
variable "md_metadata" {
  type = object({
    default_tags = map(string)
    deployment = object({
      id = string
    })
    name_prefix = string
    observability = object({
      alarm_webhook_url = string
    })
    package = object({
      created_at             = string
      deployment_enqueued_at = string
      previous_status        = string
      updated_at             = string
    })
    target = object({
      contact_email = string
    })
  })
}
variable "monitoring" {
  type = object({
    control_plane_log_retention = number
  })
}
variable "node_groups" {
  type = list(object({
    advanced_configuration_enabled = bool
    instance_type                  = string
    max_size                       = number
    min_size                       = number
    name                           = string
    advanced_configuration = optional(object({
      taint = optional(object({
        effect      = string
        taint_key   = string
        taint_value = string
      }))
    }))
  }))
}
variable "vpc" {
  type = object({
    infrastructure = object({
      arn  = string
      cidr = string
      internal_subnets = list(object({
        arn = string
      }))
      private_subnets = list(object({
        arn = string
      }))
      public_subnets = list(object({
        arn = string
      }))
    })
    specs = optional(object({
      aws = optional(object({
        region = optional(string)
      }))
    }))
  })
}
